import {
  Home,
  MessageCircle,
  Share2,
  RefreshCw,
  User,
  Image as ImageIcon,
  Users,
  Wallet,
  Palette,
  ShoppingBag,
  Mail,
  Bell,
  MessageSquare,
  Briefcase,
  Calculator,
  MapPin,
  Truck,
  PlayCircle,
  Megaphone,
  Calendar,
  type LucideIcon,
} from "lucide-react";

export const navIconMap: Record<string, LucideIcon> = {
  home: Home,
  "message-circle": MessageCircle,
  "share-2": Share2,
  "refresh-cw": RefreshCw,
  user: User,
  image: ImageIcon,
  users: Users,
  wallet: Wallet,
  palette: Palette,
  "shopping-bag": ShoppingBag,
  mail: Mail,
  bell: Bell,
  "message-square": MessageSquare,
  briefcase: Briefcase,
  calculator: Calculator,
  "map-pin": MapPin,
  truck: Truck,
  "play-circle": PlayCircle,
  megaphone: Megaphone,
  calendar: Calendar,
};