/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as MensagensChamadaRouteImport } from './routes/mensagens.chamada'
import { Route as ConfiguracoesPermissoesRouteImport } from './routes/configuracoes.permissoes'
import { Route as SocialPerfilIdRouteImport } from './routes/social.perfil.$id'

const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensChamadaRoute = MensagensChamadaRouteImport.update({
  id: '/mensagens/chamada',
  path: '/mensagens/chamada',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPermissoesRoute = ConfiguracoesPermissoesRouteImport.update({
  id: '/configuracoes/permissoes',
  path: '/configuracoes/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPerfilIdRoute = SocialPerfilIdRouteImport.update({
  id: '/social/perfil/$id',
  path: '/social/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/mensagens/chamada': typeof MensagensChamadaRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/social/perfil/$id': typeof SocialPerfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/mensagens/chamada': typeof MensagensChamadaRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/social/perfil/$id': typeof SocialPerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/mensagens/chamada': typeof MensagensChamadaRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/social/perfil/$id': typeof SocialPerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente'
    | '/catalogo'
    | '/configuracoes/permissoes'
    | '/mensagens/chamada'
    | '/configuracoes/'
    | '/social/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente'
    | '/catalogo'
    | '/configuracoes/permissoes'
    | '/mensagens/chamada'
    | '/configuracoes'
    | '/social/perfil/$id'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/catalogo'
    | '/configuracoes/permissoes'
    | '/mensagens/chamada'
    | '/configuracoes/'
    | '/social/perfil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracoesPermissoesRoute: typeof ConfiguracoesPermissoesRoute
  MensagensChamadaRoute: typeof MensagensChamadaRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  SocialPerfilIdRoute: typeof SocialPerfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/chamada': {
      id: '/mensagens/chamada'
      path: '/mensagens/chamada'
      fullPath: '/mensagens/chamada'
      preLoaderRoute: typeof MensagensChamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/permissoes': {
      id: '/configuracoes/permissoes'
      path: '/configuracoes/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof ConfiguracoesPermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/perfil/$id': {
      id: '/social/perfil/$id'
      path: '/social/perfil/$id'
      fullPath: '/social/perfil/$id'
      preLoaderRoute: typeof SocialPerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracoesPermissoesRoute: ConfiguracoesPermissoesRoute,
  MensagensChamadaRoute: MensagensChamadaRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  SocialPerfilIdRoute: SocialPerfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
