/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as ConfiguracoesPermissoesRouteImport } from './routes/configuracoes.permissoes'

const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPermissoesRoute = ConfiguracoesPermissoesRouteImport.update({
  id: '/configuracoes/permissoes',
  path: '/configuracoes/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente': typeof AgenteRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agente' | '/configuracoes/permissoes' | '/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agente' | '/configuracoes/permissoes' | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/agente'
    | '/configuracoes/permissoes'
    | '/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteRoute: typeof AgenteRoute
  ConfiguracoesPermissoesRoute: typeof ConfiguracoesPermissoesRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/permissoes': {
      id: '/configuracoes/permissoes'
      path: '/configuracoes/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof ConfiguracoesPermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteRoute: AgenteRoute,
  ConfiguracoesPermissoesRoute: ConfiguracoesPermissoesRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
