/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesPermissoesRouteImport } from './routes/configuracoes.permissoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesPermissoesRoute = ConfiguracoesPermissoesRouteImport.update({
  id: '/configuracoes/permissoes',
  path: '/configuracoes/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes/permissoes': typeof ConfiguracoesPermissoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracoes/permissoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracoes/permissoes'
  id: '__root__' | '/' | '/configuracoes/permissoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesPermissoesRoute: typeof ConfiguracoesPermissoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/permissoes': {
      id: '/configuracoes/permissoes'
      path: '/configuracoes/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof ConfiguracoesPermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesPermissoesRoute: ConfiguracoesPermissoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
